# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=16)),
                ('content', models.TextField()),
            ],
        ),
    ]
