# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('describe', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('describe', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('describe', models.CharField(max_length=256)),
            ],
        ),
    ]
