# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Company'),
        ),
    ]
