# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_me',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
