# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 13:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_auto_20170306_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='organization',
        ),
    ]
