# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about_me',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
