# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20170306_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='static/images/logos', verbose_name='logo'),
        ),
    ]
